minio-dev:
  access-key: ygvEL3wO2Q5RBKrH5fCi
  secret-key: KmipWx5wzybLihd3zSDNc1pmaqi4VGZlirHTRg85

vml:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: msp23050s1.cs.hku.hk
    port: 3306
    database: vml
    username: root
    password: 123456
python:
  server:
    #根据开发/测试环境修改
    url: http://msp23050s1.cs.hku.hk:8084
minio:
  host: http://msp23050s1.cs.hku.hk:8082